repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
# - repo: https://github.com/pycqa/isort
#   rev: 5.12.0
#   hooks:
#     - id: isort
#       name: isort (python)
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.286
  hooks:
    - id: ruff
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
