version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LITESTREAM_PLATFORM: ${LITESTREAM_PLATFORM:-arm64}
    restart: unless-stopped
    ports:
      - "13000:8000"
    env_file: .env.prod
    volumes:
      - ./db:/code/db
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
