version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "13000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=pat.settings.prod
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
