# Generated by Django 4.2 on 2023-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accomplishment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="accomplishments"),
        ),
    ]
