# Generated by Django 4.2 on 2023-08-21 23:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_accomplishment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accomplishment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path
            ),
        ),
    ]
